name: socialapp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  dio: ^4.0.6
  hexcolor: ^3.0.1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.0.9
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  custom_navigation_bar: ^0.8.2
  font_awesome_flutter: 
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.2
  pull_to_refresh: ^2.0.0
  jiffy: ^5.0.0
  flutter_spinkit: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf     


